services:
  takserver:
    #    container_name: takserver
    image: takserver-full:latest
    platform: linux/amd64
    env_file:
      - 'EDIT_ME.env'
    build:
      context: ..
      dockerfile: docker/Dockerfile.takserver
    volumes:
      - '../takdata/logs:/opt/tak/data/logs'
      - '../takdata/certs:/opt/tak/data/certs'
    entrypoint: bash /opt/tak/docker_entrypoint.sh
    networks:
      - taknet
    ports:
      - '8089:8089'
      - '8443:8443'
      - '8444:8444'
      - '8446:8446'
      - '9000:9000'
      - '9001:9001'

  takdb:
    image: postgis/postgis:16-3.4
    platform: linux/amd64
    networks:
      - taknet
    env_file:
      - 'EDIT_ME.env'
    volumes:
      - 'cluster_takserver_db_data:/var/lib/postgresql/data'

networks:
  taknet:

volumes:
  cluster_takserver_db_data:
    driver: local
